### ISSUE TITLE
拒绝连接错误connect ECONNREFUSED 127.0.0.1:8080

### ISSUE THREAD

**Issue by frewise** [stulzq/azure-openai-proxy#35]
我在docker compose up -d之后，在ChatGPT web页面发送消息后没有正常回复，报错如下：
`request to http://127.0.0.1:8080/v1/chat/completions failed, reason: connect ECONNREFUSED 127.0.0.1:8080`
请大佬帮忙看看设置是否有问题，非常感谢！yml如下：
```
services:
  chatgpt-web:
    image: chenzhaoyu94/chatgpt-web
    ports:
      - 3002:3002
    environment:
      OPENAI_API_KEY: xxxxxxxxxxxx
      OPENAI_API_BASE_URL: http://localhost:8080
      OPENAI_API_MODEL: "gpt-3.5-turbo"
      AUTH_SECRET_KEY: "Bearer"
      MAX_REQUEST_PER_HOUR: 1000
      TIMEOUT_MS: 60000
    depends_on:
      - azure-openai
    links:
      - azure-openai
    networks:
      - chatgpt-ns

  azure-openai:
    image: stulzq/azure-openai-proxy
    ports:
      - 8080:8080
    environment:
      AZURE_OPENAI_ENDPOINT: https://xxx.openai.azure.com
      AZURE_OPENAI_MODEL_MAPPER: gpt-3.5-turbo=gpt-35-turbo
      AZURE_OPENAI_API_VER: 2023-05-15
    networks:
      - chatgpt-ns

networks:
  chatgpt-ns:
    driver: bridge
```
