### ISSUE TITLE
config.yaml 不生效

### ISSUE THREAD

**Issue by yinjiahuidada** [stulzq/azure-openai-proxy#66]
docker run -p 8080:8080 --name=azure-openai-proxy \
  -v ./config.yaml:/app/config/config.yaml \
  stulzq/azure-openai-proxy:latest

error log
```  
2023/09/20 13:15:54 Init from config file
2023/09/20 13:15:54 executable path: /app/azure-openai-proxy
2023/09/20 13:15:54 read config file error: open /app/config.yaml: no such file or directory
panic: open /app/config.yaml: no such file or directory

goroutine 1 [running]:
main.main()
	github.com/stulzq/azure-openai-proxy/cmd/main.go:31 +0xfa
```

config.yaml
```
api_base: "/v1"
deployment_config:
  - deployment_name: "gpt-35-turbo"
    model_name: "gpt-3.5-turbo"
    endpoint: "xxxx"
    api_key: "xxxx"
    api_version: "2023-07-01-preview"

  - deployment_name: "text-davinci-003"
    model_name: "text-davinci-003"
    endpoint: "xxxx"
    api_key: "xxxx"
    api_version: "2023-07-01-preview"

  - deployment_name: "gpt-4"
    model_name: "gpt-4"
    endpoint: "xxxx"
    api_key: "xxxx"
    api_version: "2023-07-01-preview"



```

**Comment by yinjiahuidada** [comment]
找到问题了 
修改 
```
docker run -p 8080:8080 --name=azure-openai-proxy
-v ./config.yaml:/app/config/config.yaml
stulzq/azure-openai-proxy:latest
```
为
```
docker run -p 8080:8080 --name=azure-openai-proxy
-v ./config.yaml:/app/config.yaml
stulzq/azure-openai-proxy:latest
```

readme 中的命令是错误的
![image](https://github.com/stulzq/azure-openai-proxy/assets/41564352/b86e0f07-11e8-4875-b8a0-0f75cd03e61b)

另, 如果需要在 docker compose 中使用, 
可以把
```
azure-openai:
    image: stulzq/azure-openai-proxy
    ports:
      - 8080:8080
    environment:
      AZURE_OPENAI_ENDPOINT: <Azure OpenAI API Endpoint>
      AZURE_OPENAI_MODEL_MAPPER: <Azure OpenAI API Deployment Mapper>
      # AZURE_OPENAI_MODEL_MAPPER: gpt-4=gpt-4,gpt-3.5-turbo=gpt-35-turbo
      AZURE_OPENAI_API_VER: 2023-07-01-preview
    networks:
      - chatgpt-ns
```

替换为
```
azure-openai:
    image: stulzq/azure-openai-proxy
    ports:
      - 8080:8080
    volumes:
      - ./config.yaml:/app/config.yaml
    networks:
      - chatgpt-ns

```
