### ISSUE TITLE
Config behavior changed since v1.3.6?

### ISSUE THREAD

**Issue by PeterDaveHello** [stulzq/azure-openai-proxy#95]
I only get this error since v1.3.6, v1.3.5 works fine with the same configuration from the environment variable:

```
azure-openai     | 2024/05/12 06:35:30 Init from config file
azure-openai     | 2024/05/12 06:35:30 executable path: /app/azure-openai-proxy
azure-openai     | 2024/05/12 06:35:30 read config file error: open /app/config.yaml: no such file or directory
azure-openai     | panic: open /app/config.yaml: no such file or directory
azure-openai     |                                           
azure-openai     | goroutine 1 [running]:
azure-openai     | main.main()
azure-openai     |      github.com/stulzq/azure-openai-proxy/cmd/main.go:31 +0xfa
azure-openai exited with code 2
```

**Comment by PeterDaveHello** [comment]
Checking https://github.com/stulzq/azure-openai-proxy/releases/tag/v1.3.6, maybe this is related?

`feat: optimize read config file`
https://github.com/stulzq/azure-openai-proxy/commit/e3cd10288d3da2e464ecb8c547321d83d135d10e

**Comment by PeterDaveHello** [comment]
My `docker-compose.yml`:

```yml
  azure-openai:
    image: stulzq/azure-openai-proxy:v1.3.5
    ports:
      - 8080:8080
    environment:
      AZURE_OPENAI_ENDPOINT: https://<aoai-deployment>.openai.azure.com/
```
